language: csharp
solution: TodoApp.sln
mono: none
dotnet: 3.1.301
script:
  - dotnet tool install -g dotnet-format
  - dotnet restore
  - dotnet-format --check
  - dotnet build --no-incremental /WarnAsError
  - dotnet test
