language: csharp
solution: TodoApp.sln
mono: none
dotnet: 3.1.301
script:
  - dotnet restore
  - dotnet tool restore
  - dotnet tool run dotnet-format --check
  - dotnet build --no-incremental /WarnAsError
  - dotnet test
